apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-argoproj
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
  source:
    repoURL: https://github.com/dhpup/argoproj-quickstart.git
    targetRevision: main
    path: argocd
    directory:
      recurse: true
  destination:
    name: in-cluster
    namespace: argocd
