apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argoproj-quickstart-rollouts
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - clusters:
      selector:
        matchExpressions:
         - key: argoproj-components
           operator: In
           values:
             - "true"
  template:
    metadata:
      name: 'argoproj-quickstart-rollouts-{{.name}}'
    spec:
      destination:
        namespace: 'argo-rollouts'
        name: '{{.name}}'
      project: argoproj-quickstart
      source:
        repoURL: 'https://github.com/dhpup/argoproj-quickstart.git'
        path: 'configs/rollouts'
        targetRevision: 'main'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
